### ISSUE TITLE
Implement in react native

### ISSUE THREAD

**Issue by lucasluca** [kamgurgul/Flipper-Realm#1]
Hi! could you help me implement this library in React Native! Thanks!

**Comment by kamgurgul** [comment]
Sorry I cannot help with that because I'm not familiar with React Native and their implementation of Realm :)

**Comment by GChicha** [comment]
I've mange to use it with react-native.
I'm using the default config
```js
new Realm({schema: [...]})
```
It is necessary to follow the [getting started](https://realm.io/docs/java/latest/#getting-started) section for realm-java before.
```gradle
// android/build.gradle
  buildscript {
    dependencies {
        classpath "io.realm:realm-gradle-plugin:6.0.2"
    }
  }
```
```gradle
// android/app/build.gradle at start of the file
apply plugin: 'realm-android'
```
```java
// android/app/src/debug/java/com/example/ReactNativeFlipper.java
import java.util.Arrays;
import java.util.List;

import com.kgurgul.flipper.RealmDatabaseDriver;
import com.kgurgul.flipper.RealmDatabaseProvider;
import io.realm.Realm;
import io.realm.RealmConfiguration;

public class ReactNativeFlipper {
  public static void initializeFlipper(Context context, ReactInstanceManager reactInstanceManager) {
      // others plugins ....
      // I had to remove the existent database plugin
      // client.addPlugin(new DatabasesFlipperPlugin(context));
      client.addPlugin(new DatabasesFlipperPlugin(new RealmDatabaseDriver(context, new RealmDatabaseProvider() {
        @Override
        public List<RealmConfiguration> getRealmConfigurations() {
          Realm.init(context);
          return Arrays.asList(Realm.getDefaultConfiguration());
        }
      })));
  }
}
```

**Comment by lucasluca** [comment]
Thanks for the reply @kamgurgul GChicha but im having this issue trying to run the app
![image](https://user-images.githubusercontent.com/16627838/81979438-57c7c680-9603-11ea-952c-265237120e48.png)

**Comment by lucasluca** [comment]
i renamed ndk folder and bundlet it but on the flipper client this is how appears 
![image](https://user-images.githubusercontent.com/16627838/81981240-68c60700-9606-11ea-9ea6-ac6d130ea7f4.png)

**Comment by lucasluca** [comment]
![image](https://user-images.githubusercontent.com/16627838/81981418-a9258500-9606-11ea-9751-8c1652941714.png)
